name = "GeoPlottingHelpers"
uuid = "c20ae07a-79b5-4dbd-b2dc-f2e51386613e"
authors = ["Alberto Mengali <disberd@gmail.com>"]
version = "0.1.3-DEV"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
ScopedValues = "7e506255-f358-4e82-b7e4-beb19740aa63"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[weakdeps]
CoordRefSystems = "b46f11dc-f210-4604-bfba-323c1ec968cb"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"

[extensions]
CoordRefSystemsExt = "CoordRefSystems"
MeshesExt = "Meshes"
PlotlyBaseExt = "PlotlyBase"

[compat]
Artifacts = "1"
CoordRefSystems = "0.15, 0.16, 0.17"
Meshes = "0.52, 0.53"
PlotlyBase = "0.8.20"
ScopedValues = "1.3.0"
TOML = "1.0.3"
julia = "1.10"
